### PR TITLE
[Update] vue3 conversion

### LINKED ISSUE #2: [Improvement] Vue3 support
https://next.vuetifyjs.com/en/getting-started/installation/

### PR DESCRIPTION
**Pull request by Pk13055**
- `vue-cli-service` -> `vite`
- `vuex` -> `pinia`

This PR fixes #2

### CODE REVIEW

**Comment by Pk13055** [comment]
@gsc2001 This adds vue3 support, but is basically breaking. I would recommend adding a `vue2` branch with the current version and merging this into `main`. LGTM!

**Comment by gsc2001** [comment]
Instead of making a vue2 branch, maybe we can create a vue3 branch and push it there till it is not stable? I will also look into this as soon as I get some time.

**Comment by Pk13055** [comment]
@gsc2001 All packages are stable and production ready, so would rather create a vue2 branch since vue2 is EOL by end of year.

**Comment by Pk13055** [comment]
@gsc2001 LGTM!

**Comment by gsc2001** [comment]
Thanks for the work @Pk13055 !

**Pull request merged**
